"""Status-aware bibliographic evidence graph for Noesis.

Claim-to-source evidence graph: every important concept in the software is
traceable from a repository location to a claim, a status (S0..S6/X), a source
anchor, a limitation, and a validation gate.

Canonical inputs (single source of truth):
- ``data/sources.json``            — bibliography sources
- ``data/claim_source_ledger.json``— claims
- ``data/forbidden_claims.json``   — forbidden overclaims (status X)
- ``data/theory_vocabulary.json``  — curated theory-term guard surface

Derived artifacts (regenerated by :func:`write_generated`):
- ``data/bibliography.bib``, ``data/source_graph.json`` and the ``docs/*.md``
  bibliography documents.

No claim survives without status. No theory survives without operational
function. No source is accepted unless it anchors a claim, module, validator,
schema, metric, or limitation.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

VALID_STATUSES = frozenset({"S0", "S1", "S2", "S3", "S4", "S5", "S6", "X"})
_PROXY_OR_THEORY = frozenset(
    {"theory_claim", "analogy_claim", "proxy_claim", "limitation_claim"}
)
_THEORY_ANCHOR_TYPES = frozenset({"theory_claim", "analogy_claim", "proxy_claim"})
_THEORY_HEAVY_MIN_TERMS = 2
HUMAN_GATE = "gate11_human_responsibility"


# --------------------------------------------------------------------------- #
# Data model
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class Source:
    id: str
    authors: list[str]
    year: int
    title: str
    type: str
    domain: str
    supports: list[str]
    limits: list[str]
    used_in: list[str]
    status: str
    risk_if_overused: list[str]
    bibtex_type: str = "misc"
    venue: str = ""


@dataclass(frozen=True)
class Claim:
    claim_id: str
    claim_text: str
    claim_type: str
    status: str
    source_ids: list[str]
    repo_locations: list[str]
    module_dependency: list[str]
    validation_gate: str
    limitation: str
    failure_mode: str
    allowed_wording: str
    forbidden_wording: str


@dataclass(frozen=True)
class Forbidden:
    id: str
    claim: str
    why_forbidden: str
    safe_replacement: str
    gate_that_blocks_it: str


@dataclass(frozen=True)
class Term:
    term: str
    source_ids: list[str]


@dataclass(frozen=True)
class GateResult:
    gate: str
    passed: bool
    detail: str
    offenders: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "gate": self.gate,
            "passed": self.passed,
            "detail": self.detail,
            "offenders": self.offenders,
        }


# --------------------------------------------------------------------------- #
# Loading
# --------------------------------------------------------------------------- #
def repo_root() -> Path:
    """Walk up from this module until a directory containing ``data/`` is found."""
    here = Path(__file__).resolve()
    for parent in here.parents:
        if (parent / "data" / "sources.json").exists():
            return parent
    return here.parent.parent


def _load(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


@dataclass(frozen=True)
class Library:
    """Loaded canonical bibliography."""

    sources: list[Source]
    claims: list[Claim]
    forbidden: list[Forbidden]
    vocabulary: list[Term]
    root: Path

    @property
    def source_by_id(self) -> dict[str, Source]:
        return {s.id: s for s in self.sources}


def load_library(root: Path | None = None) -> Library:
    base = root or repo_root()
    data = base / "data"
    sources = [
        Source(**{k: v for k, v in raw.items()})
        for raw in _load(data / "sources.json")["sources"]
    ]
    claims = [Claim(**raw) for raw in _load(data / "claim_source_ledger.json")["claims"]]
    forbidden = [
        Forbidden(**raw) for raw in _load(data / "forbidden_claims.json")["forbidden_claims"]
    ]
    vocabulary = [Term(**raw) for raw in _load(data / "theory_vocabulary.json")["terms"]]
    return Library(sources, claims, forbidden, vocabulary, base)


# --------------------------------------------------------------------------- #
# Repository scan
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class ScanResult:
    files_scanned: int
    term_hits: dict[str, list[str]]  # term -> [file, ...]
    doc_terms: dict[str, list[str]]  # doc path -> [term, ...]

    @property
    def present_terms(self) -> set[str]:
        return {t for t, files in self.term_hits.items() if files}

    @property
    def theory_heavy_docs(self) -> list[str]:
        # Gate 1 anchoring applies to prose docs only, not source modules.
        return sorted(
            doc
            for doc, terms in self.doc_terms.items()
            if doc.startswith("docs/") and len(terms) >= _THEORY_HEAVY_MIN_TERMS
        )


# Bibliography meta-docs describe the bibliography system itself; they list every
# theory term by construction and are therefore excluded from the coverage scan.
_META_DOCS = frozenset(
    {
        "BIBLIOGRAPHY.md",
        "CLAIM_SOURCE_LEDGER.md",
        "BIBLIOGRAPHIC_EVIDENCE_GRAPH.md",
        "UNSUPPORTED_CLAIMS.md",
        "OVERCLAIM_GUARDRAILS.md",
        "SOURCE_STATUS_HIERARCHY.md",
        "CITATION_POLICY.md",
    }
)


def _scan_files(root: Path) -> list[Path]:
    files: list[Path] = []
    docs = root / "docs"
    if docs.is_dir():
        files.extend(sorted(p for p in docs.glob("*.md") if p.name not in _META_DOCS))
    pkg = root / "noesis"
    if pkg.is_dir():
        files.extend(sorted(p for p in pkg.glob("*.py") if p.name != "bibliography.py"))
    return files


def scan_repo(lib: Library) -> ScanResult:
    files = _scan_files(lib.root)
    term_hits: dict[str, list[str]] = {t.term: [] for t in lib.vocabulary}
    doc_terms: dict[str, list[str]] = {}
    for path in files:
        rel = path.relative_to(lib.root).as_posix()
        low = path.read_text(encoding="utf-8").lower()
        hits = [t.term for t in lib.vocabulary if t.term in low]
        if hits:
            doc_terms[rel] = hits
        for term in hits:
            term_hits[term].append(rel)
    return ScanResult(len(files), term_hits, doc_terms)


# --------------------------------------------------------------------------- #
# Validation gates
# --------------------------------------------------------------------------- #
def _all_referenced_locations(lib: Library) -> set[str]:
    locs: set[str] = set()
    for s in lib.sources:
        locs.update(s.used_in)
    for c in lib.claims:
        locs.update(c.repo_locations)
    return locs


def validate(lib: Library, scan: ScanResult | None = None) -> list[GateResult]:
    scan = scan or scan_repo(lib)
    by_id = lib.source_by_id
    results: list[GateResult] = []

    # Gate 1 — Coverage: every theory-heavy doc is anchored by a source/claim.
    anchored = _all_referenced_locations(lib)
    unanchored = [d for d in scan.theory_heavy_docs if d not in anchored]
    results.append(
        GateResult(
            "Gate 1 — Coverage",
            not unanchored,
            f"{len(scan.theory_heavy_docs)} theory-heavy docs; {len(unanchored)} unanchored",
            unanchored,
        )
    )

    # Gate 2 — Status: every claim and source carries a valid status.
    bad_status = [c.claim_id for c in lib.claims if c.status not in VALID_STATUSES]
    bad_status += [f"source:{s.id}" for s in lib.sources if s.status not in VALID_STATUSES]
    results.append(
        GateResult("Gate 2 — Status", not bad_status, "all statuses in S0..S6/X", bad_status)
    )

    # Gate 3 — Limitation: every theory/analogy/proxy/limitation claim states a limit.
    no_limit = [
        c.claim_id
        for c in lib.claims
        if c.claim_type in _PROXY_OR_THEORY and not c.limitation.strip()
    ]
    results.append(
        GateResult("Gate 3 — Limitation", not no_limit, "theory claims carry limitations", no_limit)
    )

    # Gate 4 — Forbidden mapping: every forbidden claim has a safe replacement + gate.
    bad_forbidden = [
        f.id for f in lib.forbidden if not (f.safe_replacement.strip() and f.gate_that_blocks_it.strip())
    ]
    results.append(
        GateResult(
            "Gate 4 — Forbidden mapping",
            not bad_forbidden,
            "forbidden claims have safe replacement + blocking gate",
            bad_forbidden,
        )
    )

    # Gate 5 — Source quality: ≥70% of theory anchors are primary/review.
    anchor_ids = {
        sid
        for c in lib.claims
        if c.claim_type in _THEORY_ANCHOR_TYPES
        for sid in c.source_ids
    }
    anchors = [by_id[sid] for sid in anchor_ids if sid in by_id]
    primary_review = [s for s in anchors if s.type in {"primary", "review"}]
    share = (len(primary_review) / len(anchors)) if anchors else 1.0
    results.append(
        GateResult(
            "Gate 5 — Source quality",
            share >= 0.70,
            f"{len(primary_review)}/{len(anchors)} theory anchors primary/review ({share:.0%})",
        )
    )

    # Gate 6 — Repo linkage: every source is used by ≥1 claim or ≥1 file.
    claim_refs = {sid for c in lib.claims for sid in c.source_ids}
    unlinked = [s.id for s in lib.sources if s.id not in claim_refs and not s.used_in]
    results.append(
        GateResult("Gate 6 — Repo linkage", not unlinked, "every source linked to a claim or file", unlinked)
    )

    # Gate 7 — No decorative sources: a source unused by any claim must still be
    # used_in a file (background), never fully orphaned.
    decorative = [s.id for s in lib.sources if s.id not in claim_refs and not s.used_in]
    results.append(
        GateResult("Gate 7 — No decorative sources", not decorative, "no orphaned sources", decorative)
    )

    # Gate 8 — Proxy honesty: every proxy claim says 'proxy' and names forbidden wording.
    dishonest = [
        c.claim_id
        for c in lib.claims
        if c.claim_type == "proxy_claim"
        and ("proxy" not in (c.claim_text + " " + c.allowed_wording).lower() or not c.forbidden_wording.strip())
    ]
    results.append(
        GateResult("Gate 8 — Proxy honesty", not dishonest, "proxy claims say proxy, not measurement", dishonest)
    )

    # Gate 9 — Human responsibility: a human-review gate exists and forbidden claims are blocked.
    has_human = any(c.validation_gate == HUMAN_GATE for c in lib.claims)
    blocked = all(f.gate_that_blocks_it.strip() for f in lib.forbidden)
    results.append(
        GateResult(
            "Gate 9 — Human responsibility",
            has_human and blocked,
            "high-stakes routing to human + forbidden claims blocked",
        )
    )

    # Gate 10 — Term mapping (CI): every present theory term maps to existing sources.
    offenders: list[str] = []
    vocab_by_term = {t.term: t for t in lib.vocabulary}
    for term in sorted(scan.present_terms):
        sids = vocab_by_term[term].source_ids
        if not sids:
            offenders.append(f"{term}: no source")
            continue
        missing_src = [sid for sid in sids if sid not in by_id]
        if missing_src:
            offenders.append(f"{term}: unknown source {missing_src}")
    results.append(
        GateResult(
            "Gate 10 — Term mapping",
            not offenders,
            f"{len(scan.present_terms)} present theory terms all mapped",
            offenders,
        )
    )

    return results


def gates_pass(results: list[GateResult]) -> bool:
    return all(r.passed for r in results)


# --------------------------------------------------------------------------- #
# Missing / unsupported
# --------------------------------------------------------------------------- #
def missing(lib: Library, scan: ScanResult | None = None) -> dict[str, Any]:
    scan = scan or scan_repo(lib)
    by_id = lib.source_by_id
    claim_refs = {sid for c in lib.claims for sid in c.source_ids}
    return {
        "claims_without_sources": [c.claim_id for c in lib.claims if not c.source_ids],
        "claims_speculative": [c.claim_id for c in lib.claims if c.status == "S6"],
        "sources_without_claims": [s.id for s in lib.sources if s.id not in claim_refs],
        "broken_source_refs": sorted(
            {sid for c in lib.claims for sid in c.source_ids if sid not in by_id}
        ),
        "unmapped_present_terms": sorted(
            t for t in scan.present_terms if not {x.term: x for x in lib.vocabulary}[t].source_ids
        ),
    }


# --------------------------------------------------------------------------- #
# Graph / bibtex / audit / verdict
# --------------------------------------------------------------------------- #
def build_source_graph(lib: Library) -> dict[str, Any]:
    nodes = (
        [{"id": s.id, "kind": "source", "status": s.status, "domain": s.domain} for s in lib.sources]
        + [{"id": c.claim_id, "kind": "claim", "status": c.status, "type": c.claim_type} for c in lib.claims]
    )
    edges: list[dict[str, str]] = []
    for c in lib.claims:
        for sid in c.source_ids:
            edges.append({"from": sid, "to": c.claim_id, "rel": "supports"})
        for mod in c.module_dependency:
            edges.append({"from": c.claim_id, "to": mod, "rel": "used_by_module"})
        if c.validation_gate:
            edges.append({"from": c.claim_id, "to": c.validation_gate, "rel": "guarded_by"})
    return {"nodes": nodes, "edges": edges}


def _bibtex_key(s: Source) -> str:
    return s.id


def export_bibtex(lib: Library) -> str:
    out: list[str] = ["% Generated from data/sources.json — do not edit by hand.\n"]
    for s in sorted(lib.sources, key=lambda x: x.id):
        authors = " and ".join(s.authors)
        fields = [
            f"  author    = {{{authors}}}",
            f"  title     = {{{s.title}}}",
            f"  year      = {{{s.year}}}",
        ]
        if s.venue:
            key = "journal" if s.bibtex_type == "article" else "publisher" if s.bibtex_type in {"book", "incollection"} else "howpublished"
            fields.append(f"  {key:9s} = {{{s.venue}}}")
        fields.append(f"  note      = {{status={s.status}; domain={s.domain}}}")
        out.append(f"@{s.bibtex_type}{{{_bibtex_key(s)},\n" + ",\n".join(fields) + "\n}\n")
    return "\n".join(out)


def audit(lib: Library, scan: ScanResult | None = None) -> dict[str, Any]:
    scan = scan or scan_repo(lib)
    results = validate(lib, scan)
    by_status: dict[str, int] = {}
    for c in lib.claims:
        by_status[c.status] = by_status.get(c.status, 0) + 1
    m = missing(lib, scan)
    return {
        "total_files_scanned": scan.files_scanned,
        "total_claims_extracted": len(lib.claims),
        "total_sources": len(lib.sources),
        "claims_by_status": dict(sorted(by_status.items())),
        "claims_without_sources": m["claims_without_sources"],
        "sources_without_claims": m["sources_without_claims"],
        "forbidden_claims_guarded": len(lib.forbidden),
        "proxy_claims": [c.claim_id for c in lib.claims if c.claim_type == "proxy_claim"],
        "speculative_claims": m["claims_speculative"],
        "present_theory_terms": len(scan.present_terms),
        "coverage_percent": round(100 * sum(r.passed for r in results) / len(results), 1),
        "bibliography_gate_status": "PASS" if gates_pass(results) else "FAIL",
    }


def verdict(lib: Library, scan: ScanResult | None = None) -> dict[str, Any]:
    scan = scan or scan_repo(lib)
    results = validate(lib, scan)
    return {
        "overall_status": "PASS" if gates_pass(results) else "FAIL",
        "gates": [r.to_dict() for r in results],
        "audit": audit(lib, scan),
    }


# --------------------------------------------------------------------------- #
# Document generators (derived; never hand-edit the outputs)
# --------------------------------------------------------------------------- #
_GEN_HEADER = "<!-- GENERATED from data/*.json by noesis.bibliography — do not edit by hand. -->\n"

_DOMAIN_TITLES = {
    "working_memory": "1. Working memory / PFC / cognitive control",
    "global_workspace": "2. Global Workspace / GNWT",
    "active_inference": "3. Active Inference / Free Energy / Predictive Coding",
    "distributed_cognition": "4. Distributed Cognition / Cognitive Offloading",
    "llm_orchestration": "5. Test-time LLM orchestration",
    "verification": "6. Verification / Process supervision / LLM-as-judge limits",
    "software_engineering": "7. Software engineering / architecture",
    "philosophy": "8. Philosophy / conceptual engineering / metaphysics",
}


def render_bibliography_md(lib: Library) -> str:
    claim_refs = {sid for c in lib.claims for sid in c.source_ids}
    lines = [_GEN_HEADER, "# Bibliography\n", "Grouped by domain. Each entry anchors a claim, module, or limitation.\n"]
    for domain, title in _DOMAIN_TITLES.items():
        domain_sources = [s for s in lib.sources if s.domain == domain]
        if not domain_sources:
            continue
        lines.append(f"\n## {title}\n")
        for s in sorted(domain_sources, key=lambda x: x.year):
            tag = "" if s.id in claim_refs else " _(background)_"
            authors = ", ".join(s.authors)
            lines.append(f"### `{s.id}` — {s.status}{tag}")
            lines.append(f"- **{authors} ({s.year}).** *{s.title}.* {s.venue} [{s.type}]")
            lines.append(f"- supports: {'; '.join(s.supports)}")
            lines.append(f"- limits: {'; '.join(s.limits)}")
            lines.append(f"- used in: {', '.join(f'`{u}`' for u in s.used_in)}")
            lines.append(f"- risk if overused: {'; '.join(s.risk_if_overused)}\n")
    return "\n".join(lines) + "\n"


def render_claim_ledger_md(lib: Library) -> str:
    lines = [
        _GEN_HEADER,
        "# Claim → Source Ledger\n",
        "claim → status → source → module → limitation → gate.\n",
        "| claim | type | status | sources | module | gate | limitation |",
        "|---|---|---|---|---|---|---|",
    ]
    for c in lib.claims:
        srcs = ", ".join(f"`{s}`" for s in c.source_ids) or "_none (see UNSUPPORTED)_"
        mods = ", ".join(c.module_dependency)
        lines.append(
            f"| `{c.claim_id}` | {c.claim_type} | {c.status} | {srcs} | {mods} | "
            f"`{c.validation_gate}` | {c.limitation} |"
        )
    lines.append("\n## Wording discipline\n")
    for c in lib.claims:
        lines.append(f"- **{c.claim_id}** — allowed: _{c.allowed_wording}_ · forbidden: _{c.forbidden_wording}_")
    return "\n".join(lines) + "\n"


def render_evidence_graph_md(lib: Library, scan: ScanResult) -> str:
    a = audit(lib, scan)
    lines = [
        _GEN_HEADER,
        "# Bibliographic Evidence Graph\n",
        "How claims map to sources and statuses. Canonical data lives in `data/*.json`;",
        "`data/source_graph.json` holds the machine-readable graph.\n",
        "## Status distribution",
        f"- files scanned: **{a['total_files_scanned']}**, claims: **{a['total_claims_extracted']}**, "
        f"sources: **{a['total_sources']}**, present theory terms: **{a['present_theory_terms']}**",
        f"- claims by status: `{a['claims_by_status']}`",
        f"- proxy claims: {len(a['proxy_claims'])}, speculative (S6): {len(a['speculative_claims'])}, "
        f"forbidden guarded: {a['forbidden_claims_guarded']}",
        f"- bibliography gate status: **{a['bibliography_gate_status']}**\n",
        "## Claim → sources → module → gate",
    ]
    for c in lib.claims:
        lines.append(f"\n### `{c.claim_id}` ({c.status}, {c.claim_type})")
        lines.append(f"> {c.claim_text}")
        lines.append(f"- sources: {', '.join(f'`{s}`' for s in c.source_ids) or '—'}")
        lines.append(f"- repo: {', '.join(f'`{r}`' for r in c.repo_locations)}")
        lines.append(f"- module: {', '.join(c.module_dependency)} · gate: `{c.validation_gate}`")
        lines.append(f"- failure mode: {c.failure_mode}")
    return "\n".join(lines) + "\n"


def render_unsupported_md(lib: Library, scan: ScanResult) -> str:
    m = missing(lib, scan)
    lines = [
        _GEN_HEADER,
        "# Unsupported / under-supported claims\n",
        "Honest backlog. A claim here either has no source (must be sourced or removed)",
        "or is explicitly speculative (S6) and must never be presented as validated.\n",
        "## Claims without sources",
    ]
    lines += [f"- `{cid}`" for cid in m["claims_without_sources"]] or ["- none"]
    lines.append("\n## Speculative claims (S6 — research hypotheses, not validated)")
    lines += [f"- `{cid}`" for cid in m["claims_speculative"]] or ["- none"]
    lines.append("\n## Background sources (cited in docs, not yet anchoring a ledger claim)")
    lines += [f"- `{sid}`" for sid in m["sources_without_claims"]] or ["- none"]
    if m["broken_source_refs"]:
        lines.append("\n## BROKEN source references (must fix)")
        lines += [f"- `{sid}`" for sid in m["broken_source_refs"]]
    return "\n".join(lines) + "\n"


def render_overclaim_md(lib: Library) -> str:
    lines = [
        _GEN_HEADER,
        "# Overclaim guardrails (status X — forbidden)\n",
        "Every forbidden claim has a reason, a safe replacement, and a blocking gate.",
        "Runtime enforcement: `noesis/forbidden.py` (`gate12_forbidden`).\n",
        "| forbidden claim | why forbidden | safe replacement | blocking gate |",
        "|---|---|---|---|",
    ]
    for f in lib.forbidden:
        lines.append(
            f"| {f.claim} | {f.why_forbidden} | {f.safe_replacement} | `{f.gate_that_blocks_it}` |"
        )
    return "\n".join(lines) + "\n"


def write_generated(lib: Library, scan: ScanResult | None = None) -> list[str]:
    """Regenerate all derived docs + data files. Returns written paths."""
    scan = scan or scan_repo(lib)
    docs = lib.root / "docs"
    data = lib.root / "data"
    written: list[tuple[Path, str]] = [
        (docs / "BIBLIOGRAPHY.md", render_bibliography_md(lib)),
        (docs / "CLAIM_SOURCE_LEDGER.md", render_claim_ledger_md(lib)),
        (docs / "BIBLIOGRAPHIC_EVIDENCE_GRAPH.md", render_evidence_graph_md(lib, scan)),
        (docs / "UNSUPPORTED_CLAIMS.md", render_unsupported_md(lib, scan)),
        (docs / "OVERCLAIM_GUARDRAILS.md", render_overclaim_md(lib)),
        (data / "bibliography.bib", export_bibtex(lib)),
        (data / "source_graph.json", json.dumps(build_source_graph(lib), ensure_ascii=False, indent=2) + "\n"),
    ]
    for path, content in written:
        path.write_text(content, encoding="utf-8")
    return [p.relative_to(lib.root).as_posix() for p, _ in written]
